# -*- coding: utf-8 -*-
{
    "name": "Beyond Remote Printing Base",
    "author": "REVO TECH",
    "summary": "",
    "version:": "19.0.0.7",
    "description": "",
    "depends": ["base", "mrp", "stock"],
    "data": [
        "security/group.xml",
        "security/ir.model.access.csv",
        "data/cron.xml",
        "data/data.xml",
        "views/remote_printer_server_view.xml",
        "views/remote_printer_task_view.xml",
        "views/remote_printer_views.xml",
        "views/remote_printer_menus.xml",
        "views/res_partner_views.xml",
        "views/label_content_view.xml",
        "views/label_title_view.xml",
        "views/label_type_view.xml",
        "views/stock_picking_type_view.xml",
        "wizard/direct_print_wizard.xml",
    ],
    "assets": {},
    "installable": True,
    "application": False,
    "license": "OEEL-1",
}
